language: cpp
compiler:
 - gcc

install:
 - wget http://downloads.arduino.cc/arduino-1.5.6-r2-linux64.tgz
 - ls -alF
 - tar -xvf arduino-1.5.6-r2-linux64.tgz
 - sudo mv arduino-1.5.6-r2/ /usr/local/share/arduino
 - git clone -b ide1.5x https://github.com/justonia/ino.git
 - cd ino && sudo make install && cd ../
 - sudo pip install jinja2
 - sudo pip install pyserial
 - pwd

script:
 - ino --help
 - ls -alF /usr/local/share/arduino
 - ls -alF /usr/local/share/arduino/hardware/tools
 - /usr/local/share/arduino/hardware/tools/g++_arm_none_eabi/bin/arm-none-eabi-gcc --version
 - cd blink && ino build -m arduino_due_x_dbg
